# Generated by Django 5.2 on 2025-05-04 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=30)),
                ('nome_responsavel', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_colaborador', models.CharField(max_length=30)),
                ('funcao', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarefa', models.CharField(max_length=250)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('prioridade', models.CharField(choices=[('alta', 'Alta'), ('media', 'Média'), ('baixa', 'Baixa')], max_length=30)),
                ('status', models.CharField(choices=[('abertos', 'Abertos'), ('em_espera', 'Em espera'), ('em_atraso', 'Em atraso'), ('pausados', 'Pausados'), ('nao_atribuidos', 'Não atribuídos'), ('encerram_hoje', 'Encerram hoje')], max_length=40)),
            ],
        ),
    ]
