# Generated by Django 5.2 on 2025-05-04 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os_control_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='prioridade',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Média'), ('baixa', 'Baixa')], max_length=30),
        ),
    ]
