# Generated by Django 5.2 on 2025-05-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os_control_app', '0003_alter_ordemservico_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('em_espera', 'Em espera'), ('em_atraso', 'Em atraso'), ('pausados', 'Pausados'), ('nao_atribuidos', 'Não atribuídos'), ('encerram_hoje', 'Encerram hoje')], max_length=40),
        ),
    ]
