# Generated by Django 5.2 on 2025-05-05 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os_control_app', '0005_alter_ordemservico_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Colaborador',
        ),
    ]
