# Generated by Django 5.2 on 2025-05-05 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('os_control_app', '0007_cliente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
