# Generated by Django 5.2 on 2025-05-06 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os_control_app', '0009_remove_ordemservico_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('em_espera', 'Em espera'), ('em_atraso', 'Em atraso'), ('pausado', 'Pausado'), ('nao_atribuido', 'Não atribuído'), ('encerra_hoje', 'Encerra hoje')], max_length=40, null=True),
        ),
    ]
