# Generated by Django 5.2 on 2025-05-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os_control_app', '0011_ordemservico_cliente_ordemservico_colaborador_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=30)),
                ('data_criacao', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='obs_tarefa',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
