# Generated by Django 5.2 on 2025-05-16 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os_control_app', '0012_author_alter_ordemservico_obs_tarefa'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='data_atendimento',
            field=models.DateField(null=True),
        ),
    ]
