# Generated by Django 5.2 on 2025-05-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os_control_app', '0014_alter_ordemservico_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='data_atendimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
