# Generated by Django 5.2 on 2025-05-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os_control_app', '0015_alter_ordemservico_data_atendimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='enviar_RAT',
            field=models.FileField(blank=True, null=True, upload_to='file_uploads/'),
        ),
    ]
